### ISSUE TITLE
Not Posible Change Logo in Every App and Favicon

### ISSUE THREAD

**Issue by tjaoc** [uilibrary/Stocky-Issues-and-Feature-request#2]

**Comment by naime-hossain** [comment]
> _No description provided._

can you elaborate on your query? you can change logo from system settings

**Comment by tjaoc** [comment]
Yes, but not change the favicon, not change the loading, not change the login login, not change footer logo........

**Comment by naime-hossain** [comment]
Fixed , Updated code will be upload in codecanyon

**Comment by teehanming** [comment]
Hello, is this fixed? because I just bought and use it, it still not update the whole logo, only the dashboard logo

**Comment by naime-hossain** [comment]
we will check and fix if there an issue, don't worry :)
