### ISSUE TITLE
settings not changing -> issue solved after enable PHP fileinfo extenstion

### ISSUE THREAD

**Issue by ramijd1** [uilibrary/Stocky-Issues-and-Feature-request#38]
hello there ,, i have successfully installed the script, but whenever i try to change the setting i got invalid data message :\ https://i.imgur.com/n1D1NYR.png please help .

**Comment by ramijd1** [comment]
well i find that the issue happened when i change the logo .

**Comment by hamzakifani** [comment]
Hope your issue is fixed and let us know if you need any further help.

Great Job. if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items Your review will motivate us to thank you

**Comment by ramijd1** [comment]
the issue is not solved , whenever i change logo i have data invalid message , also when i change image in user profile same problem :(

**Comment by hamzakifani** [comment]
if you are using cpanel try to check if you are enable "Fileinfo PHP extension" ?

**Comment by hamzakifani** [comment]
sinon nous envoyer une capture de la console lorsque vous avez essayé de changer de logo

**Comment by hamzakifani** [comment]
check if all thèse extension enabled

![inst](https://user-images.githubusercontent.com/50219942/115975387-f10d9580-a553-11eb-9bf2-7eacd47c3927.PNG)

**Comment by ramijd1** [comment]
good , that solve the problem

**Comment by hamzakifani** [comment]
Great Job. if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items Your review will motivate us to thank you

**Comment by naime-hossain** [comment]
I am Closing the issue, if you need any further help please create a new issue and let us know :) if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items Your review will motivate us to thank you
