### ISSUE TITLE
Modification

### ISSUE THREAD

**Issue by zubiridoz** [uilibrary/Stocky-Issues-and-Feature-request#85]
Hello, This is awesome product. Is there any chance to get developer guide for any single module (ex. Product Module). I just want to see the road map of the single module code. or Code flow of the crud. Thank You.

I would also like to know how the language is modified, since the translation is wrong.

Regards

**Comment by hamzakifani** [comment]
Hi . We will add developer guide soon .
If you need  change  translation 
1) Go to /resources/src/translations/locales
2) run : npm install
3) run : npm run watch
4) run : npm run prod

**Comment by zubiridoz** [comment]
Hi, thanks for your response.
As I can predefine only the Spanish language and deactivate the others.

**Comment by hamzakifani** [comment]
if you want to make a default language 

1) Go to /resources/src/plugins/i18n.js
![i18n](https://user-images.githubusercontent.com/50219942/117990149-689d3c00-b32c-11eb-9a4c-d563fb4244ca.PNG)

2) Next replace ;

locale: 'en',
fallbackLocale: 'en',

to : 

locale: 'es',
fallbackLocale: 'es',

3) run : npm install
4) run : npm run watch
5) run : npm run prod

**Comment by c300** [comment]
I edited en.js to adapt to mu language and executed 3,4,5 then reuploaded in the server all files, but yet i can not see the updated language.

**Comment by naime-hossain** [comment]
Hope your issue is fixed. if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

**Comment by c300** [comment]
> Hope your issue is fixed. if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)

My issue is not fixed, please read it again if you can help me.

**Comment by ugur010** [comment]
Hello, when you make changes to the Tur.js in the Translation, it does not change. I could not find their files in different places. Can you help me? I want to manually edit these languages.
